version: "3.9"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://${GCP_VM_IP}:${GCP_SPRING_DATASOURCE_PORT}/${GCP_SPRING_DATASOURCE_DBNAME}
      SPRING_DATASOURCE_USERNAME: ${GCP_SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${GCP_SPRING_DATASOURCE_PASSWORD}
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"   # 브라우저 접근용
    restart: always
    depends_on:
      - backend

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${GCP_SPRING_DATASOURCE_PASSWORD}
      MYSQL_DATABASE: ${GCP_SPRING_DATASOURCE_DBNAME}
    ports:
      - "3306:3306"
    restart: always
    command: --default-authentication-plugin=mysql_native_password
