version: "3.9"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://${{ secrets.GCP_VM_IP }}:${{ secrets.GCP_SPRING_DATASOURCE_PORT }}/${{ secrets.GCP_SPRING_DATASOURCE_DBNAME }}
      SPRING_DATASOURCE_USERNAME: ${{ secrets.GCP_SPRING_DATASOURCE_USERNAME }}
      SPRING_DATASOURCE_PASSWORD: ${{ secrets.GCP_SPRING_DATASOURCE_PASSWORD }}
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"   # 브라우저 접근용
    depends_on:
      - backend

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${{ secrets.GCP_SPRING_DATASOURCE_USERNAME }}
      MYSQL_DATABASE: ${{ secrets.GCP_SPRING_DATASOURCE_PASSWORD }}
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
