spring:
  application:
    name: MAPro
    
  # AWS RDS MySQL 직접 연결
  datasource:
    url: jdbc:mysql://keyword-02.cbyqikm2gos5.ap-northeast-2.rds.amazonaws.com:3306/mapro?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: dev
    password: Dev1010**
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        
  security:
    jwt:
      secret: mapro-secret-key-2024-very-long-secret-key-for-jwt-token-generation
      expiration: 86400000

server:
  port: 8080

logging:
  level:
    com.groom.MAPro: DEBUG
    root: INFO