name: Build and Push Chat API Image

on:
  push:
    branches: [ "dev/BEchat" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker to use gcloud as a credential helper
      run: gcloud auth configure-docker asia-northeast3-docker.pkg.dev

    - name: Build and push Docker image
      run: |
        IMAGE_NAME=asia-northeast3-docker.pkg.dev/custom-sun-466702-d5/docker-repo/mapro-chat-api:latest
        docker build --no-cache -t $IMAGE_NAME .
        docker push $IMAGE_NAME
        echo "✅ Chat API image built and pushed successfully!"
