name: Deploy Python Script to GCP VM (python-branch)

on:
  push:
    branches:
      - python-branch

jobs:
  deploy-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.GCP_ACTIONS_KEY }}

      - name: Copy Python files to GCP VM
        run: |
          scp -r ./ nakedflower02@<${{ secrets.GCP_SPRING_DATASOURCE_HOST }}>:/home/nakedflower02/python_project

      - name: Run Python script on GCP VM
        run: |
          ssh nakedflower02@<${{ secrets.GCP_SPRING_DATASOURCE_HOST }}> "cd ~/python_project && python3 your_script.py"
