name: Build and Push to GCR and Deploy to VM

on:
  push:
    branches: [ "dev/BEreview" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker to use gcloud as a credential helper
      run: gcloud auth configure-docker asia-northeast3-docker.pkg.dev

    - name: Build and push Docker image
      run: |
        IMAGE_NAME=asia-northeast3-docker.pkg.dev/custom-sun-466702-d5/docker-repo/mapro-python-review:latest
        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME

    - name: Deploy to GCP VM
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.GCP_VM_IP }}
        username: ${{ secrets.NF_GCP_VM_USER }}
        key: ${{ secrets.NF_GCP_SSH_KEY }}
        port: 22
        script: |
          IMAGE_NAME=asia-northeast3-docker.pkg.dev/custom-sun-466702-d5/docker-repo/mapro-python-review:latest
          gcloud auth configure-docker asia-northeast3-docker.pkg.dev
          docker pull $IMAGE_NAME
          docker stop mapro-container-review || true
          docker rm mapro-container-review || true
          docker run -d --name ${{ env.CONTAINER_NAME }} \
            -e GCP_VM_IP="${{ secrets.GCP_VM_IP }}" \
            -e GCP_SPRING_DATASOURCE_USERNAME="${{ secrets.GCP_SPRING_DATASOURCE_USERNAME }}" \
            -e GCP_SPRING_DATASOURCE_PASSWORD="${{ secrets.GCP_SPRING_DATASOURCE_PASSWORD }}" \
            -e GCP_SPRING_DATASOURCE_DBNAME="${{ secrets.GCP_SPRING_DATASOURCE_DBNAME }}" \
            -e GOOGLE_MAPS_API_KEY="${{ secrets.GOOGLE_MAPS_API_KEY }}" \
            $IMAGE_NAME
